# Generated by Django 3.2.4 on 2021-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers_phone', models.CharField(max_length=14, null=True)),
                ('passengers_name', models.CharField(max_length=100, null=True)),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datatime', models.DateField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('seats', models.IntegerField(null=True)),
                ('price', models.FloatField(null=True)),
                ('arrival', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_where', to='trip.district')),
            ],
        ),
    ]
