# Generated by Django 3.2.4 on 2021-06-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='bus',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.bus'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_where', to='trip.district'),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.driver'),
        ),
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.district'),
        ),
        migrations.AddField(
            model_name='ordertrip',
            name='trip',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='trip.trip'),
        ),
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.province'),
        ),
    ]
