# Generated by Django 3.2.3 on 2021-06-15 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_bus_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.driver'),
        ),
    ]
