# Generated by Django 3.2.3 on 2021-06-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_driver_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ImageField(upload_to='drivers'),
        ),
    ]
