# Generated by Django 3.2.3 on 2021-06-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_driver_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='image',
            field=models.ImageField(upload_to='Buses'),
        ),
    ]
